In [2]:
import numpy as np

In [3]:
# 3 dimension array
arr = np.arange(0, 4*2*4)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [4]:
# 차원 변환
v = arr.reshape([4, 2, 4]) # row, col, depth
v
# 0, 8, 16, 24: row
# 0, 4: col
# 0, 1, 2, 3: depth

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [5]:
v.ndim
# sum 함수의 axis 파라미터의 기본값은 “None”입니다.
# axis는 대상 데이터의 Dimension보다 작은 값을 설정합니다.
# 예제 데이터의 Dimension은 3이기 때문에 axis는 2까지 설정 가능합니다.

3

# axis=None

In [6]:
v.sum() # scalar

496

# axis =0

In [8]:
res01 = v.sum(axis=0) # row sum
print(res01.shape) # 4*2*4 -> 2*4
print(res01)

(2, 4)
[[48 52 56 60]
 [64 68 72 76]]


# axis=1

In [9]:
res02 = v.sum(axis=1)
print(res02.shape) # 4*2*4 -> 4 * 4
print(res02)

(4, 4)
[[ 4  6  8 10]
 [20 22 24 26]
 [36 38 40 42]
 [52 54 56 58]]


# axis=2

In [10]:
res03 = v.sum(axis=2)
print(res03.shape) # 4*2*4 -> 4*2
print(res03)

(4, 2)
[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]]


# Reference
$\blacktriangleright$ TAEWAN.KIM 블로그
http://taewan.kim/post/numpy_sum_axis/